# Generated by Django 2.2.2 on 2019-07-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EcommApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.BooleanField()),
                ('wshishlist', models.BooleanField()),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommApp.customers')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommApp.products')),
            ],
        ),
    ]
